import React, { useEffect } from "react";
import { generateAuthUrl } from "../helper functions/generateAuthUrl";

function Login () {
    // okay, the thing is: useEffect keeps executing window.location.href before it can do its thing.
    // update: actually, the problem seems to be elsewhere because redirecting to another link outsiide the app works normally
    // update: if i jump directly to the link generated by generateAuthUrl(), the thing still ends up in an infinite loop.
    function redirect () {
        window.location.href = generateAuthUrl();
    }
    

    useEffect(() => {
        //setTimeout(redirect, 4000);
        window.location.href = generateAuthUrl();   // if access token isn't null, this works normally:
                                                    // a completely new access token is obtained

    }, [])
 
    return null;
}

export default Login;